#
# Memento
# Docker Compose
# Development Stack
#

version: "3.4"
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - database-data:/var/lib/postgresql/data
  # memento-backend container
  backend:
    image: "mrzzy/memento-backend:latest"
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
      target: develop
    ports:
      - "5000:5000"
    env_file: ".env"
    depends_on:
      - postgres
    volumes:
      - "./src/backend:/backend:ro"
volumes:
  database-data:
