#
# Memento
# Docker Compose
# Development Stack
#

version: "3.4"
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - database-data:/var/lib/postgresql/data
  backend:
    image: "mrzzy/memento-backend:1.0-apiv1"
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
      target: production
      args:
        API_VERSION: 1
    ports:
      - "5000:5000"
    env_file: ".env"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    volumes:
      - "./src/backend:/backend" 
  frontend:
    image: "mrzzy/memento-frontend:1.0-apiv1"
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - postgres
    volumes:
      - "./src/frontend:/frontend" 
volumes:
  database-data:
