{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "memento.serviceAccountName" . }}
  labels:
{{ include "memento.labels" . | indent 4 }}
{{- end -}}
