# 
# Memento
# Helm Chart
# Secrets
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memento.fullname" . }}-database
  labels:
{{ include "memento.labels" . | indent 4 }}
stringData:
  POSTGRES_USER: {{ .Values.credentials.database.user }}
  POSTGRES_PASSWORD: {{ .Values.credentials.database.password }}
