# 
# Memento
# Helm Chart
# Secrets
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memento.fullname" . }}-secrets
  labels:
{{ include "memento.labels" . | indent 4 }}
stringData:
  {{- .Files.Get ".env" | replace "=" ": " | nindent 2 -}}
