# 
# Memento
# Helm Chart
# Environment Configmap
#

{{ $dbPort := .Values.services.database.port -}}
{{ $dbSvcName := .Values.services.database.name -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memento.fullname" . }}-config-env
  labels:
{{ include "memento.labels" . | indent 4 }}
data:
  # postgres config
  POSTGRES_DB: memento
  # backend config
  FLASK_APP: "app.py"
  SQL_DATABASE: postgresql
  DATABASE_HOST: "{{ $dbSvcName }}:{{ $dbPort }}"
  SQLALCHEMY_TRACK_MODIFICATIONS: "0"
  SQLALCHEMY_ECHO: "0"
