# 
# Memento
# Helm Chart
# Environment Configmap
#

{{ $fullName := include "memento.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memento.fullname" . }}-config-env
  labels:
{{ include "memento.labels" . | indent 4 }}
data:
  # postgres config
  POSTGRES_DB: memento

  # backend config
  FLASK_APP: app.py
  SQL_DATABASE: postgresql
  DATABASE_HOST: "{{ $fullName }}-database:{{ .Values.services.database.port }}"
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  SQLALCHEMY_ECHO: false
