# 
# Memento
# Helm Chart
# Backend Service
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "memento.fullname" . }}-backend
  labels:
{{ include "memento.labels" . | indent 4 }}
    component: backend
spec:
  type: {{ .Values.services.backend.type }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
      app: {{ include "memento.fullname" . }}
      component: backend
