# 
# Memento
# Helm Chart
# Database Service
#

apiVersion: v1
kind: Service
metadata: 
  name:  {{ .Values.services.database.name }}
  labels:
{{ include "memento.labels" . | indent 4 }}
    component: database
spec:
  type: {{ .Values.services.database.type }}
  ports:
    - port: {{ .Values.services.database.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
      app: {{ include "memento.fullname" . }}
      component: database
